### ISSUE TITLE
Parou de funcionar

### ISSUE THREAD

**Issue by Yuji84** [hugombarreto/guiabolso2csv#15]
Após uma atualização do guia bolso, o script parou de funcionar.
Retorno:
Traceback (most recent call last):
  File "/usr/local/bin/guiabolso2csv", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/guiabolso2csv/__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "/usr/local/lib/python3.7/dist-packages/guiabolso2csv/guia_bolso.py", line 71, in __init__
    for account in self.statements:
TypeError: 'NoneType' object is not iterable

**Comment by RobsonArgolo** [comment]
Mesmo aqui... parou... possivelmente pq eles colocaram uma funcionalidade p0rka no modelo de assinatura deles. Pagaria a assinatura se me permitisse extrair "meus dados" via API


**eventNotFound
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Robson\gb2csv\guiabolso2csv\__main__.py", line 59, in <module>
    main()
  File "C:\Users\Robson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Robson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Robson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Robson\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Robson\gb2csv\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "C:\Users\Robson\gb2csv\guiabolso2csv\guia_bolso.py", line 55, in __init__
    self.token = self.login()
  File "C:\Users\Robson\gb2csv\guiabolso2csv\guia_bolso.py", line 111, in login
    raise Exception(response['payload']['code'])
Exception: NO_EVENT_HANDLER_FOUND
**

**Comment by marlindo71** [comment]
Dêem uma olhada nessa issue https://github.com/hsadok/guiabolso2csv/issues/10#issuecomment-839278861

**Comment by RobsonArgolo** [comment]
Funcionou com a nova versão !! obrigado
