### ISSUE TITLE
Não valida nem extrai o arquivo

### ISSUE THREAD

**Issue by And-Rochaa** [hugombarreto/guiabolso2csv#16]
Faço o procedimento coloco login e senha, porém aparece essa mensagem:

Traceback (most recent call last):
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\Scripts\guiabolso2csv.exe\__main__.py", line 7, in <module>
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 55, in __init__
    self.token = self.login()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 107, in login
    response = self.session.post(url, headers=headers, data=payload).json()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\asrpj>guiabolso2csv --email asrpja@gmail.com --year 2021 --month 11
Password:
Password:
Traceback (most recent call last):
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\Scripts\guiabolso2csv.exe\__main__.py", line 7, in <module>
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 55, in __init__
    self.token = self.login()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 107, in login
    response = self.session.post(url, headers=headers, data=payload).json()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

C:\Users\asrpj>guiabolso2csv --email asrpja@gmail.com --year 2021 --month 11
Password:
Traceback (most recent call last):
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\Scripts\guiabolso2csv.exe\__main__.py", line 7, in <module>
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\__main__.py", line 40, in main
    gb = GuiaBolso(email, password)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 55, in __init__
    self.token = self.login()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\guiabolso2csv\guia_bolso.py", line 107, in login
    response = self.session.post(url, headers=headers, data=payload).json()
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\site-packages\requests\models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\asrpj\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by felipejrvieira** [comment]
Acredito que o seu problema será resolvido seguindo as orientações desse comentário. https://github.com/hsadok/guiabolso2csv/issues/10#issuecomment-839278861

Utilizo esse fork para fazer a extração das informações.

**Comment by And-Rochaa** [comment]
Amigo, não estou conseguindo achar o token conforme orientado, loguei no site mas em console não aparece nenhum token.

![image](https://user-images.githubusercontent.com/56509577/144474685-743697bd-2053-47bb-b704-4272fc95a984.png)

Saberia dizer o que pode ser ?

**Comment by And-Rochaa** [comment]
> Amigo, não estou conseguindo achar o token conforme orientado, loguei no site mas em console não aparece nenhum token.
> 
> ![image](https://user-images.githubusercontent.com/56509577/144474685-743697bd-2053-47bb-b704-4272fc95a984.png)
> 
> Saberia dizer o que pode ser ?

**Comment by And-Rochaa** [comment]
> 



> Acredito que o seu problema será resolvido seguindo as orientações desse comentário. [#10 (comment)](https://github.com/hsadok/guiabolso2csv/issues/10#issuecomment-839278861)
> 
> Utilizo esse fork para fazer a extração das informações.

https://github.com/hsadok/guiabolso2csv/issues/16#issuecomment-984820884

**Comment by And-Rochaa** [comment]
> Acredito que o seu problema será resolvido seguindo as orientações desse comentário. [#10 (comment)](https://github.com/hsadok/guiabolso2csv/issues/10#issuecomment-839278861)
> 
> Utilizo esse fork para fazer a extração das informações.

Amigo, nao estou conseguindo achar o token, no console não aprece.

Saberia dizer o que seria ?

![image](https://user-images.githubusercontent.com/56509577/144475104-ad14339b-a94f-421e-9bd7-1ee40ceb3414.png)

**Comment by felipejrvieira** [comment]
Então nessa tela do console do chrome, após logar no guiabolso, você vai usar o comando abaixo

`JSON.parse(localStorage.getItem("login")).token`

Assim que você executar esse comando, aparecerá o token. Este token você colará no prompt.
Obs: Lembre-se de tirar as aspas do começo e do fim.

**Comment by And-Rochaa** [comment]
> Então nessa tela do console do chrome, após logar no guiabolso, você vai usar o comando abaixo
> 
> `JSON.parse(localStorage.getItem("login")).token`
> 
> Assim que você executar esse comando, aparecerá o token. Este token você colará no prompt. Obs: Lembre-se de tirar as aspas do começo e do fim.

Deu certo agora amigo, muito obrigado.
